#!/bin/bash

GOARCH=amd64 GOOS=darwin go build -o artifacts/importer-darwin-amd64 && \
GOARCH=arm64 GOOS=darwin go build -o artifacts/importer-darwin-arm64 && \
CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o artifacts/importer-linux-amd64
